name: jupyterlab
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pangeo-notebook=2023.09.17
  - jupyterhub
  - jupyterlab
  - bash_kernel
  - r-irkernel
  - scikit-image
  - scikit-learn
  - seaborn
  - nodejs
  - cdsdashboards
  - cdsdashboards-singleuser
  - panel
  - dash
  - plotly
  - jupyter-dash
  - voila
  - pip
  - pip:
      # make sure to use this commit - 92606b9933d81605e44665cdc1b646b37b41f95b
      - git+https://github.com/jupyterhub/batchspawner.git@main
      - aws-parallelcluster==3.5.0
      - aws-pcluster-helpers>3.5
      - aws-pcluster-slurm-spawner>3.5
      - aws-pcluster-dask-gateway>3.5
      - jupyter-dcv-proxy
      - jupyter-containds
