name: quilt
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - click
  - pandas
  - pyarrow
  - dask
  - nodejs
  - pip:
      - devtools
      - colorlog
      - quilt3[catalog,pyarrow]
