# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: schrodinger-2022-3
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - compilers
  - python
  - ipython
