name: jupyterlab
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pangeo-notebook=2022.05.10
  - dask-gateway-server-jobqueue
  - jupyter-rsession-proxy
  - jupyterhub
  - jupyterlab
  - scikit-image
  - scikit-learn
  - seaborn
  - bash_kernel
  - nodejs
  - prefect>=2
  - cdsdashboards
  - cdsdashboards-singleuser
  - voila
  - pip
  - pip:
      - batchspawner
      - aws-parallelcluster==3.3.1
      - aws-pcluster-helpers
      - aws-pcluster-slurm-spawner
      - aws-pcluster-dask-gateway
      - jupyter-dcv-proxy
      - jupyter-vscode-proxy
      - prefect>=2
      - prefect-aws
      - prefect-shell
      - jupyter-containds
