name: pyautofep 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - typer
  - pydantic
  - rich-click
  - cython
  - ipython
  - ipykernel
  - pandas
  - seaborn
  - bash_kernel
  - matplotlib
  - numpy
  - scipy
  - ambertools
  - parallel
  - pymbar==3.0.5
  - alchemlyb=0.6.0
  - rdkit=2019.09
  - networkx>=2
  - openbabel>=3
  - biopython
  - mdanalysis
  - pip
